name: Build & push other images

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & push base image"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    uses: mairie-de-saint-jean-cap-ferrat/basic-env/.github/workflows/_build-and-push.yml@main
    strategy:
      matrix:
        image: [dart, java, javascript, typescript, php, python]
    with:
      image: ${{ matrix.image }}