name: Build & push base image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: mairie-de-saint-jean-cap-ferrat/basic-env/.github/workflows/_build-and-push.yml@main
    with:
      image: base